### ISSUE TITLE
使用WEB API查询后端出错

### ISSUE THREAD

**Issue by WangBoee** [OwO-Network/nexttrace-enhanced#4]
## 你正在使用哪个版本的 nexttrace？

v0.1.9-beta.5 linux_amd64

## 你看到的异常现象是什么？
WEB端测试，按下`查询`按钮后，保持下图状态，服务端nexttrace报错并马上终止

![image](https://user-images.githubusercontent.com/29994612/174699937-1f6abe5b-e5df-4c8d-bc46-d9de67b4a8dc.png)

在终端直接查询则没有问题，命令 `nexttrace 1.1.1.1`

![image](https://user-images.githubusercontent.com/29994612/174700735-60e4db8f-d95e-47bd-94bd-f2c6ae29e430.png)
## 请附上出错时软件输出的错误信息
```
NextTrace Enhanced v0.1.9-beta.5 2022-06-20T23:39:13Z b6b2d6d
OwO Network Leo (leo.moe) & Vincent (vincent.moe) & zhshch (xzhsh.ch)
[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.

[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
 - using env:   export GIN_MODE=release
 - using code:  gin.SetMode(gin.ReleaseMode)

[GIN-debug] GET    /                         --> github.com/xgadget-lab/nexttrace/web.Start.func1 (3 handlers)
[GIN-debug] GET    /trace                    --> github.com/xgadget-lab/nexttrace/web.Start.func2 (3 handlers)
[GIN-debug] [WARNING] You trusted all proxies, this is NOT safe. We recommend you to set a value.
Please check https://pkg.go.dev/github.com/gin-gonic/gin#readme-don-t-trust-all-proxies for details.
[GIN-debug] Listening and serving HTTP on :8888
[GIN] 2022/06/21 - 09:39:34 | 200 |     409.153µs |  117.189.235.73 | GET      "/"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7abdcf]

goroutine 13 [running]:
github.com/xgadget-lab/nexttrace/ipgeo.sendIPRequest(...)
        github.com/xgadget-lab/nexttrace/ipgeo/leo.go:32
github.com/xgadget-lab/nexttrace/ipgeo.LeoIP({0xc0003becf0, 0xa})
        github.com/xgadget-lab/nexttrace/ipgeo/leo.go:77 +0x16f
github.com/xgadget-lab/nexttrace/trace.(*Hop).fetchIPData(0xc0000bfea0, {0x1, 0x1e, 0x1, 0x12, 0x23c34600, {0xc0003be9e0, 0x10, 0x10}, 0x50, ...})
        github.com/xgadget-lab/nexttrace/trace/trace.go:124 +0xd9
github.com/xgadget-lab/nexttrace/trace.(*ICMPTracer).send(0xc00040c270, 0x1)
        github.com/xgadget-lab/nexttrace/trace/icmp_ipv4.go:170 +0x8ec
created by github.com/xgadget-lab/nexttrace/trace.(*ICMPTracer).Execute
        github.com/xgadget-lab/nexttrace/trace/icmp_ipv4.go:54 +0x2f8
```

**Comment by sjlleo** [comment]
现在应该好了，等 Github Action 编译完成 `v0.1.9-beta.6 linux_amd64` 再试试

**Comment by WangBoee** [comment]
OK了，目前一切工作正常

![image](https://user-images.githubusercontent.com/29994612/174704885-85bf0f23-5d34-4c22-852f-e20b9019de7c.png)![image](https://user-images.githubusercontent.com/29994612/174704823-cfa10e0b-de21-4736-91a2-ae2b8ba0bcaf.png)
